title: "Patryk Kaminiecki"
description: >
  <div style="text-align:center;">
    <img src="Me.jpg?raw=true" alt="Patryk Kaminiecki"
         style="border-radius:50%; width:150px; height:150px;">
  </div>

  <br><br>
  Business Analyst | Data Transformation & Reporting Expert (Power BI, Tableau, SQL) | 10+ Years in Financial Services  

  <br><br>
  <div style="text-align:center;">
    <a href="https://www.linkedin.com/in/patrykkaminiecki/" target="_blank">
      <img src="https://cdn-icons-png.flaticon.com/512/174/174857.png" 
           alt="LinkedIn" width="30" height="30" style="vertical-align:middle; border-radius:5px;">
      &nbsp; View My Profile
    </a>
    &nbsp;&nbsp;
    <a href="mailto:PatrykKaminiecki@gmail.com">
      ✉️ Contact Me
    </a>
  </div>
google_analytics: GTM-MHD4RLFF
theme: jekyll-theme-minimal
