title: "Patryk Kaminiecki"
logo: "Me.jpg?raw=true"
description: >
  Business Analyst | Data Transformation & Reporting Expert (Power BI, Tableau, SQL) | 10+ Years in Financial Services  

  <a href="https://www.linkedin.com/in/patrykkaminiecki/">View My LinkedIn Profile</a>
google_analytics: GTM-MHD4RLFF
theme: jekyll-theme-minimal
