title: Patryk KAMINIECKI
logo: Me.jpg
description: Business Analyst | Data Transformation & Reporting Expert (Power BI, Tableau, SQL) | 10+ Years in Financial Services
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
