title: "Patryk Kaminiecki"
description: >
  <div style="text-align:center;">
    <img src="Me.jpg?raw=true" alt="Patryk Kaminiecki"
         style="border-radius:50%; width:150px; height:150px;">
  </div>

  <br><br>
  <div style="text-align:center; font-weight:bold;">
    Business Analyst | Data Transformation & Reporting Expert (Power BI, Tableau, SQL) | 10+ Years in Financial Services
  </div>

  <br><br>
  <div style="text-align:center;">
    <a href="https://www.linkedin.com/in/patrykkaminiecki/" target="_blank"
       style="display:block; background:linear-gradient(90deg, #0066A2, #0077B5); color:white; padding:12px; 
              text-decoration:none; border-radius:8px; font-weight:bold; margin:10px auto; width:250px;">
      <img src="https://cdn-icons-png.flaticon.com/512/174/174857.png" 
           alt="LinkedIn" width="20" height="20" style="vertical-align:middle; margin-right:8px;">
      View My Profile
    </a>

    <a href="mailto:PatrykKaminiecki@gmail.com"
       style="display:block; background:linear-gradient(90deg, #444, #FF0000); color:white; padding:12px; 
              text-decoration:none; border-radius:8px; font-weight:bold; margin:10px auto; width:250px;">
      <img src="https://cdn-icons-png.flaticon.com/512/732/732200.png" 
           alt="Email" width="20" height="20" style="vertical-align:middle; margin-right:8px;">
      Contact Me
    </a>
  </div>
google_analytics: GTM-MHD4RLFF
theme: jekyll-theme-minimal
